spring:
  datasource:
    url: jdbc:mysql://10.50.40.145:3306/lv?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: cdwk-3g-145
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8001
logging:
  level:
    com.eairlv.cli.dao: DEBUG
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.eairlv.cli.entity.dto,com.eairlv.cli.entity.vo
  global-config:
    banner: false